CREATE TABLE roles (
  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(20),
   CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   username VARCHAR(20),
   email VARCHAR(50),
   password VARCHAR(120),
   CONSTRAINT pk_users PRIMARY KEY (id),
   CONSTRAINT uc_74165e195b2f7b25de690d14a UNIQUE (email),
   CONSTRAINT uc_77584fbe74cc86922be2a3560 UNIQUE (username)
);

CREATE TABLE user_roles (
  role_id INT NOT NULL,
   user_id BIGINT NOT NULL,
   CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id),
   CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES roles (id),
    CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE TABLE car_service (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   title VARCHAR(255),
   address VARCHAR(255),
   owner VARCHAR(255),
   CONSTRAINT pk_car_service PRIMARY KEY (id)
);
CREATE TABLE master (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   firstname VARCHAR(255),
   lastname VARCHAR(255),
   specialization VARCHAR(255),
   city VARCHAR(255),
   car_service_id BIGINT,
   rating BLOB,
   CONSTRAINT pk_master PRIMARY KEY (id),
   CONSTRAINT FK_MASTER_ON_CAR_SERVICE FOREIGN KEY (car_service_id) REFERENCES car_service (id)
);

